namespace Microlithic.Text.Ansi.Element;

///----------------------------------------------------------------------------
/// <summary>
/// Represents a parsed element generated by an
/// <see cref="AnsiStreamParser"/> instance.
/// </summary>
///
/// <remarks>
/// The callback function for <see cref="AnsiStreamParser"/> will receive
/// records implementing this interface. These records hold either a single
/// printable character, a single character from a control string, or a
/// single control or escape sequence parsed from the input stream.
/// </remarks>
///----------------------------------------------------------------------------
public interface IAnsiStreamParserElement {}
